_BASE_: "./diffdet.carDD.res101.yaml"
MODEL:
  WEIGHTS: "output_carDD_res101/torchvision-R-101.pkl"
  RESNETS:
    DEFORM_ON_PER_STAGE: [True, True, True, True]
    DEFORM_MODULATED: False
    DEFORM_NUM_GROUPS: 1
  ROI_HEADS:
    NUM_CLASSES: 6

OUTPUT_DIR: ./output_carDD_res101_dcn

