_BASE_: "Base-DiffusionDet.yaml"

MODEL:
  WEIGHTS: "output_carDD_res101/torchvision-R-101.pkl"
  RESNETS:
    DEPTH: 101
    STRIDE_IN_1X1: False
  
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 6
  
  ROI_HEADS:
    NUM_CLASSES: 6

DATASETS:
  TRAIN: ("carDD_train",)
  TEST:  ("carDD_test",)

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.000025
  STEPS: (15000, 18000)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 2000
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 1.0
  CLIP_GRADIENTS:
      ENABLED: True
      CLIP_TYPE: "full_model"
      CLIP_VALUE: 1.0
      NORM_TYPE: 2.0

INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"

TEST:
  EVAL_PERIOD: 1000

OUTPUT_DIR: ./output_carDD_res101
